"""
Sphinx configuration file. This file serves to provide the information needed to
generate HTML and PDF based documentation for the Feronia project. Be advised,
generators other than HTML and PDF are not supported by the Feronia team.

For a list of configuration options not specified here, please see
http://is.gd/0n9l6I.
"""

### General configuration. ###

# The document name of the “master” document, that is, the document that
# contains the root toctree directive. Default is 'contents'.
master_doc = "toc"

# The name of the default domain. Can also be None to disable a default domain.
# The default is 'py'. Those objects in other domains (whether the domain name
# is given explicitly, or selected by a default-domain directive) will have the
# domain name explicitly prepended when named (e.g., when the default domain is
# C, Python functions will be named “Python function”, not just “function”).
primary_domain = "cpp"

# If true, Sphinx will warn about all references where the target cannot be
# found. Default is False. You can activate this mode temporarily using the -n
# command-line switch.
nitpicky = True

### Project information. ###

# The documented project’s name.
project = "Feronia"

# A copyright statement in the style '2008, Author Name'.
copyright = "2012, Corks Development Group"

# The major project version, used as the replacement for |version|. For example,
# for the Python documentation, this may be something like 2.6.
version = "1.0"

# The default language to highlight source code in. The default is 'python'. The
# value should be a valid Pygments lexer name, see Showing code examples for
# more details.
highlight_language = "cpp"

# The code for the language the docs are written in. Any text automatically
# generated by Sphinx will be in that language. Also, Sphinx will try to
# substitute individual paragraphs from your documents with the translation sets
# obtained from locale_dirs. In the LaTeX builder, a suitable language will be
# selected as an option for the Babel package. Default is None, which means that
# no translation will be done.
language = "en"
